import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#e0e3e5",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#653e00",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-fixed": "#dbe1ff",
        "surface-tint": "#0053db",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#ffb95f",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#38485d",
        "inverse-on-surface": "#eff1f3",
        "surface-container-high": "#e6e8ea",
        "secondary-container": "#d0e1fb",
        "surface-dim": "#d8dadc",
        "on-secondary-container": "#54647a",
        "on-error-container": "#93000a",
        "primary-container": "#00174b",
        "on-secondary-fixed": "#0b1c30",
        "inverse-surface": "#2d3133",
        "background": "#f7f9fb",
        "on-primary-container": "#497cff",
        "outline": "#76777d",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#45464d",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "secondary": "#505f76",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed": "#ffddb8",
        "error-container": "#ffdad6",
        "inverse-primary": "#b4c5ff",
        "on-secondary": "#ffffff",
        "surface": "#f7f9fb",
        "tertiary-container": "#2a1700",
        "on-surface": "#191c1e",
        "tertiary": "#000000",
        "surface-container-highest": "#e0e3e5",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#b87500",
        "surface-container-low": "#f2f4f6",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
